---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src
  label: src
  create: none
  match: _**/*,*
- type: document
  path: src/_layouts/home.liquid
  label: home liquid
- type: document
  path: src/index.md
  label: home
- type: heading
  label: Heading
upload_dir: src/images
public_path: images
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: output
  install_dependencies_command: bundle config path vendor/bundle && bundle install
    &&  yarn install
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle config path vendor/bundle && yarn start
