---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/index.md
  label: home
- type: document
  path: https://github.com/pedrocarmona/pedrocarmona.github.io/tree/master/src/_posts
  label: Blog
- type: heading
  label: Heading
upload_dir: images
public_path: src/images
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_docker_image: andrewmcodes/bridgetown-gh-pages-action@v0.0.3
  install_dependencies_command: bundle config path vendor/bundle && bundle install &&  yarn install
  instant_preview_command: yarn serve
  mount_path: "/srv"
  working_dir: "/srv"
  preview_output_directory: "output"

